version: "3.9"

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.5
    container_name: wazuh-manager
    restart: unless-stopped
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
      - "514:514/udp"
    volumes:
      - wazuh_manager_data:/var/ossec/data
      - wazuh_manager_logs:/var/ossec/logs

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.7.5
    container_name: wazuh-indexer
    restart: unless-stopped
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.5
    container_name: wazuh-dashboard
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - wazuh.indexer
      - wazuh.manager

volumes:
  wazuh_manager_data:
  wazuh_manager_logs:
